name: Unit Tests

on:
  push:
    branches:
      - feature/*

jobs:
  unit-tests:
    name: Run unit tests
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Restore application dependencies
        run: dotnet restore

      - name: Build application
        run: dotnet build

      - name: Run unit tests
        run: dotnet test

  
  
